### PR TITLE
Initial version of Reviewer Guidelines

### PR DESCRIPTION
**Pull request by jackkoenig**

### CODE REVIEW

**Review by chick — APPROVED** [review]
This looks good to me.

**Comment by jackkoenig** [comment]
I apparently don't have write access to this repo 😬

**Comment by ucbjrl** [comment]
Shouldn't Jack be a member of Chisel Reviewers and shouldn't Chisel
Reviewers have write access to the repository?

**Comment by ucbjrl** [comment]
Whoops. I added FIRRTL Admins to have admin access.

**Review by azidar — APPROVED** [review]

**Pull request merged**
